Update.

diff --git a/.github/workflows/commit.yml b/.github/workflows/commit.yml
--- a/.github/workflows/commit.yml
+++ b/.github/workflows/commit.yml
@@ -78,13 +78,15 @@ jobs:
               exit 1
             fi
 
-            if [[ -e ./Cargo.lock ]] ; then
-              # Offline prevents it from updating packages that haven't been updated locally.
-              if ! cargo generate-lockfile --locked ; then
-                echo "Cargo.lock for $d not up to date; please run ./scripts/ready-pull-request.sh and resubmit."
-                exit 1
-              fi
-            fi
+            # Disabling this for now as a check; fails way too often. 
+            #
+            # if [[ -e ./Cargo.lock ]] ; then
+            #   # Offline prevents it from updating packages that haven't been updated locally.
+            #  if ! cargo generate-lockfile --locked ; then
+            #    echo "Cargo.lock for $d not up to date; please run ./scripts/ready-pull-request.sh and resubmit."
+            #    exit 1
+            #  fi
+            # fi
 
             popd
           done
