Relax the scripts checking cargo fmt requirements. (#406)
cargo fmt sometimes has false positives, which is annoying for getting
PRs submitted! This relaxes the requirements a bit.

---------

Co-authored-by: Hoyt Koepke <hoytak@xethub.com>

diff --git a/.github/workflows/commit.yml b/.github/workflows/commit.yml
--- a/.github/workflows/commit.yml
+++ b/.github/workflows/commit.yml
@@ -67,25 +67,26 @@ jobs:
             if [[ ! -e "$d/Cargo.toml" ]] ; then 
               continue
             fi
-
-            pushd $d
-              #  cargo format.
-              cargo fmt
-              cargo clippy -r --verbose -- -D warnings # elevates warnings to errors
               
-              if [[ -n "$(git status --porcelain)" ]] ; then
-                echo "cargo fmt not run; please run scripts/ready-pull-request.sh and resubmit."
-                exit 1
-              fi
+            pushd $d
+            
+            cargo clippy -r --verbose -- -D warnings # elevates warnings to errors
 
-              if [[ -e ./Cargo.lock ]] ; then
-                cargo generate-lockfile
+            #  cargo format.
+            if ! cargo fmt --check ; then 
+              echo "cargo fmt not run; please run ./scripts/ready-pull-request.sh and resubmit."
+              exit 1
+            fi
 
-                if [[ -n "$(git status --porcelain)" ]] ; then
-                  echo "Cargo.lock for $d not up to date; please run scripts/ready-pull-request.sh and resubmit."
-                  exit 1
-                fi
-              fi
+            # Disabling this for now as a check; fails way too often. 
+            #
+            # if [[ -e ./Cargo.lock ]] ; then
+            #   # Offline prevents it from updating packages that haven't been updated locally.
+            #  if ! cargo generate-lockfile --locked ; then
+            #    echo "Cargo.lock for $d not up to date; please run ./scripts/ready-pull-request.sh and resubmit."
+            #    exit 1
+            #  fi
+            # fi
 
             popd
           done
